# Association Rule Mining

### Import data

In [2]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest, f_classif
from mlxtend.frequent_patterns import apriori, association_rules

data = pd.read_csv('pd_speech_features.csv', sep=',')
data = data.sort_values('id', ascending=True)
data = data.groupby('id').mean().reset_index()


print(data.shape)

(252, 755)

In [3]:
data.head(5)

,id,gender,PPE,DFA,RPDE,numPulses,numPeriodsPulses,meanPeriodPulses,stdDevPeriodPulses,locPctJitter,...,tqwt_kurtosisValue_dec_28,tqwt_kurtosisValue_dec_29,tqwt_kurtosisValue_dec_30,tqwt_kurtosisValue_dec_31,tqwt_kurtosisValue_dec_32,tqwt_kurtosisValue_dec_33,tqwt_kurtosisValue_dec_34,tqwt_kurtosisValue_dec_35,tqwt_kurtosisValue_dec_36,class
0,0,1.0,0.823387,0.696370,0.567250,235.333333,234.333333,0.008220,0.000073,0.001963,...,1.561733,2.862000,12.293333,9.717500,9.055300,6.259100,4.021533,4.164333,22.961700,1.0
1,1,0.0,0.415637,0.793993,0.592453,213.333333,211.000000,0.008884,0.001849,0.005790,...,4.918567,4.827133,6.117633,8.599667,5.737233,7.933133,5.490533,4.941833,4.467233,1.0
2,2,1.0,0.801973,0.619967,0.520563,319.333333,318.333333,0.006041,0.000104,0.002217,...,41.129400,31.201933,14.584467,5.446800,3.462000,4.772067,9.176633,11.848100,5.552367,1.0
3,3,0.0,0.828707,0.626097,0.537183,493.000000,492.000000,0.003913,0.000042,0.000757,...,1.677633,1.908400,2.842167,3.493867,3.282433,3.085267,3.184433,4.032933,22.773633,1.0
4,4,0.0,0.831287,0.779397,0.726717,362.666667,361.666667,0.005622,0.002023,0.003593,...,4.104600,4.285233,2.953200,2.799933,2.645100,2.811367,7.268333,13.338833,63.766900,1.0

### Feature Selection

In [14]:
X = data.drop(columns=['class'])
y = data['class'].values

kbest_classifier = SelectKBest(score_func=f_classif, k=10)
kbest_classifier.fit_transform(X,y)

kbest_columns = kbest_classifier.get_support(indices=True)
kbest_df = data.iloc[:,kbest_columns]

kbest_df.head(5)

,mean_MFCC_2nd_coef,std_8th_delta_delta,std_9th_delta_delta,tqwt_stdValue_dec_11,tqwt_stdValue_dec_12,tqwt_minValue_dec_11,tqwt_minValue_dec_12,tqwt_maxValue_dec_11,tqwt_maxValue_dec_12,tqwt_kurtosisValue_dec_27
0,2.868933,0.013342,0.021728,0.004519,0.003775,-0.038598,-0.050074,0.039194,0.050074,1.546500
1,2.909100,0.015878,0.013229,0.004287,0.015735,-0.101033,-0.134677,0.098804,0.131953,7.049367
2,-0.431677,0.014602,0.013638,0.014023,0.040322,-0.069765,-0.153913,0.067104,0.147457,1.581967
3,0.497686,0.018224,0.016633,0.007439,0.034667,-0.068975,-0.136643,0.059328,0.136643,2.382533
4,3.326100,0.016386,0.016954,0.001815,0.005032,-0.015796,-0.023543,0.017359,0.023543,3.881267

### Preprocessing